[package]
name = "photo_renamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
fehler = "1.0"
log = "0.4"
log4rs = "1.1"
thiserror = "1.0"
